### ISSUE TITLE
App Bar Node List Reordering

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds-web#17]
**Is your feature request related to a problem? Please describe.**

Overall, the list of nodes in the app bar dropdown appears to be in alphabetical order, but the Geosciences entry is listed out of order.

<img width="365" alt="Screen Shot 2020-12-02 at 12 04 20" src="https://user-images.githubusercontent.com/931107/100925198-89688800-3496-11eb-83ea-4dc94ffb9455.png">

**Describe the solution you'd like**

The "Geosciences" entry should appear after "Cartography and Imaging Sciences".

**Describe alternatives you've considered**

None

**Additional context**

N/A

**Applicable requirements**

None

**Comment by myche** [comment]
I think it is alphabetical by acronym, which I think is unfortunate.

**Comment by c-suh** [comment]
I will also apply these changes (rename IMG to CIS and reorder GEO to be after CIS) wherever relevant, i.e. [Contact Us](https://pds.nasa.gov/contact/contact.shtml) and [PDS Node Descriptions](https://pds.nasa.gov/contact/contact.shtml).

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl will check what says the PDS4 standard

**Comment by jordanpadams** [comment]
@c-suh let's keep the acronym IMG since it pops up several times in the IM. @myche agrees. if folks get really upset, we should update the IM first.

https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#attribute_pds_dd_attribute_full_pds_steward_id
https://pds.nasa.gov/datastandards/documents/im/v1/index_1E00.html#attribute_pds_sip_deep_archive_pds_provider_site_id

**Comment by myche** [comment]
Thanks for maintaining *IMG* as our acronym/moniker.  We can burn the other bridges after we cross them...
